import Project from '../models/Project.js';
import { generateAgentResponse } from '../services/aiService.js';
import AdmZip from 'adm-zip';

export const getProjects = async (req, res, next) => {
    try {
        const projects = await Project.find({ user: req.user._id }).sort({ createdAt: -1 });
        res.status(200).json(projects);
    } catch (error) {
        next(error);
    }
};

export const getProjectById = async (req, res, next) => {
    try {
        const project = await Project.findOne({ _id: req.params.id, user: req.user._id });
        if (!project) return res.status(404).json({ message: 'Project not found' });
        res.status(200).json(project);
    } catch (error) {
        next(error);
    }
};

// Generates the initial boilerplate and structure for the VFS
export const createProject = async (req, res, next) => {
    try {
        const { name, prompt } = req.body;
        if (!name || !prompt) return res.status(400).json({ message: 'Name and prompt required.' });

        const initialFileSystem = {
            'package.json': JSON.stringify({
                name: name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase(),
                version: "1.0.0",
                scripts: { "dev": "vite", "start": "node server/index.js" },
                dependencies: { "react": "^18.2.0", "express": "^4.18.2", "mongoose": "^8.0.0" }
            }, null, 2),
            'README.md': `# ${name}\n\nGenerated by Lovable V2 AI.\n\nDescription: ${prompt}`,
            'server/index.js': `const express = require('express');\nconst app = express();\n\napp.get('/api', (req, res) => res.json({ message: 'Hello from API!' }));\n\napp.listen(3000, () => console.log('Server running on port 3000'));`,
            'client/src/App.jsx': `import React from 'react';\n\nexport default function App() {\n  return (\n    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">\n      <h1 className="text-3xl font-medium text-gray-800">Welcome to ${name}</h1>\n    </div>\n  );\n}`
        };

        const newProject = await Project.create({
            user: req.user._id,
            name,
            prompt,
            fileSystem: initialFileSystem,
            messages: [
                { role: 'user', content: `Initialize project: ${prompt}` },
                { role: 'assistant', content: 'I have successfully bootstrapped your Full Stack MERN application. What feature should we build first?' }
            ]
        });
        res.status(201).json(newProject);
    } catch (error) {
        next(error);
    }
};

// Handles iterative chat and multi-agent file modifications
export const chatProject = async (req, res, next) => {
    try {
        const { message } = req.body;
        const project = await Project.findOne({ _id: req.params.id, user: req.user._id });
        
        if (!project) return res.status(404).json({ message: 'Project not found' });
        if (!message) return res.status(400).json({ message: 'Message is required' });

        // Build the current VFS string representation for the LLM
        let currentFilesText = 'CURRENT VIRTUAL FILE SYSTEM:\n---\n';
        for (const [filepath, content] of Object.entries(project.fileSystem)) {
            currentFilesText += `File: ${filepath}\n\`\`\`\n${content}\n\`\`\`\n\n`;
        }

        const systemInstruction = `You are a 10x Full Stack AI Architect. You are collaborating with the user to build a complete App.
You have access to the user's File System. Whenever they request a feature, you must write or modify the EXACT code required across all relevant files (Frontend, Backend, Config).

You MUST respond strictly in the following JSON format. Do NOT wrap your output in markdown blocks.
{
  "assistantResponse": "A very brief conversational reply explaining what you built. No markdown code blocks.",
  "fileOperations": [
    { "action": "CREATE", "file": "path/example.js", "content": "full code..." },
    { "action": "UPDATE", "file": "path/example.js", "content": "full code..." },
    { "action": "DELETE", "file": "path/old.js" }
  ]
}

Only return the JSON. Never output conversational text outside the JSON. Ensure your stringified code content is properly escaped.

${currentFilesText}`;

        // Add user message to history
        project.messages.push({ role: 'user', content: message });
        
        // Pass to Gemini
        let aiJson;
        try {
            const rawResponse = await generateAgentResponse({
                systemPrompt: systemInstruction,
                messages: [{ role: 'user', content: message }],
                requireJson: true
            });
            const cleaned = rawResponse.trim().replace(/^```json/, '').replace(/```$/, '');
            aiJson = JSON.parse(cleaned);
        } catch (error) {
            console.error("AI Parse Error", error);
            // If it failed to parse, fallback to a system message
            project.messages.push({ role: 'assistant', content: "I encountered an error trying to write those files. Let's try breaking the request down." });
            await project.save();
            return res.status(500).json({ message: 'AI Agent failed to format the code properly. Please try again.', project });
        }

        // Apply File Operations
        if (aiJson.fileOperations && Array.isArray(aiJson.fileOperations)) {
            for (const op of aiJson.fileOperations) {
                if (op.action === 'CREATE' || op.action === 'UPDATE') {
                    if (op.file && op.content !== undefined) {
                        project.fileSystem[op.file] = op.content;
                    }
                } else if (op.action === 'DELETE') {
                    if (op.file) {
                        delete project.fileSystem[op.file];
                    }
                }
            }
            project.markModified('fileSystem');
        }

        // Add assistant reply
        const displayReply = aiJson.assistantResponse || 'I have updated your codebase.';
        project.messages.push({ role: 'assistant', content: displayReply });
        project.version += 1;

        await project.save();
        res.status(200).json(project);

    } catch (error) {
        next(error);
    }
};

export const exportProjectZip = async (req, res, next) => {
    try {
        const project = await Project.findOne({ _id: req.params.id, user: req.user._id });
        if (!project) return res.status(404).json({ message: 'Project not found' });

        const zip = new AdmZip();
        
        for (const [filepath, content] of Object.entries(project.fileSystem)) {
            zip.addFile(filepath, Buffer.from(content, 'utf8'));
        }

        const zipBuffer = zip.toBuffer();

        res.set('Content-Type', 'application/zip');
        res.set('Content-Disposition', `attachment; filename=${project.name.replace(/\\s+/g, '_')}_export.zip`);
        res.set('Content-Length', zipBuffer.length);
        
        res.send(zipBuffer);

    } catch (error) {
        next(error);
    }
};
