import { generateAgentResponse } from './aiService.js';
import { getCodegenSystemPrompt, buildCodegenUserMessage } from './prompts/codegenPrompt.js';

/**
 * Generates complete code files from a blueprint.
 * This is Step 2 of the 2-step AI pipeline.
 */
export const generateCodeFromBlueprint = async (blueprint, prompt) => {
    const systemPrompt = getCodegenSystemPrompt();
    const userMessage = buildCodegenUserMessage(blueprint, prompt);

    const rawResponse = await generateAgentResponse({
        systemPrompt,
        messages: [{ role: 'user', content: userMessage }],
        requireJson: true
    });

    // Clean and parse the response
    const cleaned = rawResponse
        .trim()
        .replace(/^```json\s*/i, '')
        .replace(/^```\s*/i, '')
        .replace(/\s*```$/i, '');

    try {
        const result = JSON.parse(cleaned);

        // Handle both { files: {...} } and direct { "path": "content" } formats
        let fileSystem = {};
        if (result.files && typeof result.files === 'object') {
            fileSystem = result.files;
        } else {
            // Treat the entire object as a file map
            fileSystem = result;
        }

        // Validate we got at least some files
        const fileCount = Object.keys(fileSystem).length;
        if (fileCount < 3) {
            throw new Error(`Only ${fileCount} files generated — expected at least 3 for a proper project.`);
        }

        // Ensure README exists
        if (!fileSystem['README.md']) {
            fileSystem['README.md'] = `# ${blueprint.name}\n\n${blueprint.description || ''}\n\nGenerated by AI App Builder.\n\n## Tech Stack\n- React + Vite\n- Express.js\n- MongoDB\n\n## Getting Started\n1. Install dependencies: \`npm install\`\n2. Start the server: \`cd server && npm start\`\n3. Start the client: \`cd client && npm run dev\``;
        }

        return fileSystem;
    } catch (parseError) {
        console.error('[CodegenService] Failed to parse codegen JSON:', parseError.message);
        console.error('[CodegenService] Raw response (first 500 chars):', cleaned.substring(0, 500));
        throw new Error('AI failed to generate valid code. Please try again.');
    }
};
