/**
 * Generates a complete React + Vite + Tailwind boilerplate.
 * This is used to seed new projects so the AI doesn't have to generate boilerplate.
 */
export const getViteReactTailwindTemplate = (projectName) => {
    return {
        // --- Root Files ---
        'README.md': `# ${projectName}\n\nGenerated by AI Full Stack App Builder.\n\n## Tech Stack\n- Frontend: React + Vite + Tailwind CSS + Framer Motion\n- Backend: Node.js + Express + MongoDB\n\n## Getting Started\n\n### Start Frontend\n\`\`\`bash\ncd client\nnpm install\nnpm run dev\n\`\`\`\n\n### Start Backend\n\`\`\`bash\ncd server\nnpm install\nnpm run dev\n\`\`\``,
        '.gitignore': 'node_modules\n.env\ndist\nbuild\n.DS_Store\n',
        
        // --- Client (Frontend) Boilerplate ---
        'client/package.json': JSON.stringify({
            name: `${projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-client`,
            private: true,
            version: '1.0.0',
            type: 'module',
            scripts: {
                dev: 'vite',
                build: 'vite build',
                lint: 'eslint .',
                preview: 'vite preview'
            },
            dependencies: {
                react: '^18.3.1',
                'react-dom': '^18.3.1',
                'react-router-dom': '^6.26.2',
                'lucide-react': '^0.446.0',
                'framer-motion': '^11.9.0',
                zustand: '^5.0.0',
                clsx: '^2.1.1',
                'tailwind-merge': '^2.5.2'
            },
            devDependencies: {
                '@types/react': '^18.3.9',
                '@types/react-dom': '^18.3.0',
                '@vitejs/plugin-react': '^4.3.1',
                autoprefixer: '^10.4.20',
                postcss: '^8.4.47',
                tailwindcss: '^3.4.13',
                vite: '^5.4.8'
            }
        }, null, 2),
        
        'client/vite.config.js': `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n  server: {\n    proxy: {\n      '/api': 'http://localhost:5000'\n    }\n  }\n});`,
        
        'client/tailwind.config.js': `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};`,
        
        'client/postcss.config.js': `export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};`,
        
        'client/index.html': `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>\${projectName}</title>\n    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">\n    <script src="https://cdn.tailwindcss.com"></script>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>`,
        
        'client/src/index.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  font-family: 'Inter', sans-serif;\n  background-color: #f9fafb;\n  color: #111827;\n}`,
        
        'client/src/main.jsx': `import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.jsx';\nimport './index.css';\n\ncreateRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);`,
        
        'client/src/App.jsx': `import React from 'react';\n\nfunction App() {\n  return (\n    <div className="min-h-screen flex items-center justify-center bg-gray-50">\n      <div className="text-center">\n        <h1 className="text-4xl font-normal text-gray-900 mb-4">Welcome to ${projectName}</h1>\n        <p className="text-gray-500 font-normal">Your application is ready to be built.</p>\n      </div>\n    </div>\n  );\n}\n\nexport default App;`,

        // --- Server (Backend) Boilerplate ---
        'server/package.json': JSON.stringify({
            name: `${projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-server`,
            version: '1.0.0',
            type: 'module',
            scripts: {
                start: 'node index.js',
                dev: 'nodemon index.js'
            },
            dependencies: {
                cors: '^2.8.5',
                dotenv: '^16.4.5',
                express: '^4.21.0',
                mongoose: '^8.7.0'
            },
            devDependencies: {
                nodemon: '^3.1.7'
            }
        }, null, 2),

        'server/index.js': `import express from 'express';\nimport cors from 'cors';\nimport dotenv from 'dotenv';\n\ndotenv.config();\nconst app = express();\n\napp.use(cors());\napp.use(express.json());\n\napp.get('/api/health', (req, res) => {\n  res.json({ status: 'ok', message: 'Server is running' });\n});\n\nconst PORT = process.env.PORT || 5000;\napp.listen(PORT, () => console.log(\`Server running on port \${PORT}\`));`,
    };
};
